### ISSUE TITLE
Compte des points de capacités

### ISSUE THREAD

**Issue by Qaw** [ZigmundKreud/cof#10]
Création d'un personnage guerrier demi-orque niveau 1. Juste la classe et la race ont été choisis.
Je vois Points de capacités 1/2 ... il a hérité de Vision dans le noir de la race, mais ça ne devrait pas compter.

**Comment by ZigmundKreud** [comment]
Fixed ! 
https://github.com/ZigmundKreud/cof/commit/3c06032011852738e7a4fe78d4e0bbaef8d703bb
