### ISSUE TITLE
[Amélioration] Créer une catégorie "Déroulement du combat"

### ISSUE THREAD

**Issue by revilofr** [ZigmundKreud/cof#116]
Concernant les feuilles de NPC Rencontre :  il manque peut être une catégorie  "Déroulement du combat" de manière à ce que le MJ sache quelle va être sa stratégie de combat (telle qu'elle est présenté dans la boite de base de Chroniques Oubliées).

**Comment by Qaw** [comment]
Tu peux l'ajouter dans la description, ça ne suffit pas ?

**Comment by revilofr** [comment]
C'est largement suffisant ! merci
