### ISSUE TITLE
[Amélioration] Améliorer les objets de soin

### ISSUE THREAD

**Issue by revilofr** [ZigmundKreud/cof#118]
Pour que les objets de soin soient consommables et remettent automatiquement des points de vie c'est très simple :

Il suffit de :
- les déclarer en tant que **consommable**
- Déclarer un **effet magique**
- Sélectionner **soin**
- saisir "1d8" dans la case *soin* le cas d'une potion de vie 

Je l'ai biensur fait de mon coté, mais ce pourait être de base dans le compendium.

Suggestion liée : "Rajouter la "Trousse de soin" qui est identique, sauf qu'elle ne remet qu'un seul point de vie et ne coute qu'1 pa.

**Comment by Qaw** [comment]
N'hésites pas à proposer un compendium mis à jour, tu peux attacher le fichier .db à l'issue

**Comment by revilofr** [comment]
N'y a t'il pas moyen d'exporter le compendium en json ou xml ?

**Comment by Qaw** [comment]
J'ai modifié la potion de soins dans la version 0.8.9.2
Je laisse de côté la trousse de soins car elle n'est pas dans l'équipement du DRS.
