### ISSUE TITLE
Contenu du DRS

### ISSUE THREAD

**Issue by FalconPilot** [ZigmundKreud/cof#135]
Je me demandais, est-ce que l'absence du contenu du DRS est lié à la quantité de contenu qu'il y aurait à ajouter, ou à un problème de droits d'auteur rendant l'intégration impossible ? Si ce n'est pas lié à une incompatibilité légale, je pourrais être tenté de créer une PR pour ajouter un compendium intégrant le contenu du DRS disponible publiquement. Sinon... Tant pis :( !

**Comment by Qaw** [comment]
Cherche COF-SRD dans les modules 😉

**Comment by FalconPilot** [comment]
Wow, j'avais pas vu, merci beaucoup ! :)
