### ISSUE TITLE
Compatibilité V10

### ISSUE THREAD

**Issue by FalconPilot** [ZigmundKreud/cof#136]
Salut !
Je me demandais, est-ce qu'une mise à jour vers FoundryVTT en V10 est envisagée ou non ?

**Comment by ZigmundKreud** [comment]
Bonjour @FalconPilot, 
BBE a racheté les droits sur ce système communautaire afin d'en sortir une version officielle.
Ce système n'est donc plus maintenu.

Nous sommes actuellement en train de développer la version officielle qui sera compatible v10.
Nous vous tiendrons au courant de la sortie de la prochaine version du système via le canal #chroniques-oubliées sur le Discord "La Fonderie" (https://discord.gg/pPSDNJk).
