### ISSUE TITLE
Profil custom = PM0

### ISSUE THREAD

**Issue by Quenpo** [ZigmundKreud/cof#14]
Hello,

Lorsqu'on crée un profil custom avec un carac d'incantation, les PM restent à 0

**Comment by ZigmundKreud** [comment]
C'est normal car dans COF la formule de calcul des PM dépend du profil.

**Comment by ZigmundKreud** [comment]
Je pourrais rajouter un champ dans l'éditeur de profil qui détermine si le profil est "classique" dans le calcul de PM ou si les PM sont doublés comme pour le mage et l'ensorceleur.

**Comment by ph0k** [comment]
Je laisse un commentaire ici parce que je pense que le problème a la même origine. A la création d'un profil hybride (ici rôdeur / voleur), impossible de passer le dé de vie manuellement à 1d6. Il repasse à chaque fois à 1d8.

**Comment by ZigmundKreud** [comment]
@ph0k comme je te l'avais dit sur le discord, le mieux pour ça c'est de créer une profil custom qui mélange les voies des deux classes. Techniquement il s'agit d'un nouveau profil car le système ne permet pas d'avoir deux profils en simultané.

**Comment by ZigmundKreud** [comment]
@Quenpo j'ai rajouté un champ dans l'éditeur de profil qui permet de choisir un "Multiplicateur de PM".
Par défaut ce multiplicateur est à 0, mais pour les prêtres/druides/bardes, il est à x1, pour les magiciens, les nécromants et ensorceleurs il est à x2.
Jusqu'à présent c'était plutôt mal géré.
Maintenant, cela me permet de gérer de façon "générique" les profils customs de type caster avec un nombre de PM qui peut varier d'un profil à l'autre.
