### ISSUE TITLE
#{DOWNLOAD}# Invalid URL

### ISSUE THREAD

**Issue by CopperGiraffe** [ZigmundKreud/cof#142]
Hello, 

Il me semble que le dernier commit cab37a7 introduit un bug dans le fichier `system.json` (les variables ne semblent pas bien remplacées). Du coup impossible de récupérer le système de jeu sur FVT en l’état.

Merci pour le boulot en tout cas, hâte de tester ça :)

**Comment by Qaw** [comment]
Effectivement. Un déploiement automatique qui n'était pas fonctionnel.
C'est corrigé en 11.315.2
