### ISSUE TITLE
Lien compendium

### ISSUE THREAD

**Issue by Quenpo** [ZigmundKreud/cof#15]
Hello !
Lorsque j'ai essayé de mettre les capacités dans les voies à partir du compendium, ça ne marche pas... ça crée la ligne rang 1 mais il n'y a pas le nom de la capacité, je peux pas cliquer dessus ni la supprimer. Pareil pour les rangs suivants.

**Comment by ZigmundKreud** [comment]
Comme tu l'as justement deviné c'est un bug qui est lié au fait que tes voies pointent vers des capacités qui n'existent plus (celles qui venaient de ton "monde"). Ce qu'il faut que je fasse c'est de supprimer les ID des capacités qui n'existent pas.

**Comment by ZigmundKreud** [comment]
Fixed.
Je ferai une vidéo pour expliquer comment faire des compendiums sans risquer d'avoir des liens brisés.
Pour plus de clarté j'ai ajouté des messages d'erreurs lorsque des liens étaient cassés.
