### ISSUE TITLE
Dialogue pour le lancé de dés lors d'une attaque - bonus compté double

### ISSUE THREAD

**Issue by nicolasvillatte** [ZigmundKreud/cof#18]
Le bonus d'attaque est compté double, il devrait être à zéro dans la fenêtre de dialogue puisqu'il est déjà inclus dans la valeur "mod". La case bonus de ce dialogue ne sert que lorsque'un MJ donne un bonus situationnel et donc à la main.

**Comment by ZigmundKreud** [comment]
Fixé dans le prochain commit.
