### ISSUE TITLE
PC actuel par défaut resté à 3, il devrait correspondre par défaut à la PC base + bonus de CHA

### ISSUE THREAD

**Issue by nicolasvillatte** [ZigmundKreud/cof#19]
Lors de la création d'un nouveau personnage, le PC base est bien à 2 pour un personnage avec un bonus CHA +0, mais la valeur par défaut est à 3.

**Comment by ZigmundKreud** [comment]
J'ai mergé un peu vite...en fait le fonctionnement initial était celui qui était attendu:
- la valeur de base des PC est bien de 3 + modificateur de CHA
- Les bonus correspondent aux bonus de PC accordés par le MJ.
- La valeur actuelle correspond à la valeur courante, une fois que le joueur en a dépensé une partie.

Donc mettre la valeur de base en valeur fixe à 3 et le bonus = mod. de CHA empêche l'attribution de points de chances bonus.
