### ISSUE TITLE
PC / bonus ne réflète pas le bonus de CHA, il est ajouté à la base directement à la place

### ISSUE THREAD

**Issue by nicolasvillatte** [ZigmundKreud/cof#20]
La case Bonus pour les PC ne contient pas le bonus de CHA.
Si un personnage a un bonus de CHA celui-ci est ajouté à la base au lieu d'être mis dans cette case.

**Comment by ZigmundKreud** [comment]
Oui c'est le fonctionnement attendu, la valeur de base est égale à 3 + CHA.
La case bonus est éditable par le joueur pour des bonus de PC accordés par le MJ.
