### ISSUE TITLE
PC / Actuel ne prend pas en compte le score de PC/Bonus dans le calcul

### ISSUE THREAD

**Issue by nicolasvillatte** [ZigmundKreud/cof#21]
Le score actuel de PC ne tient pas compte du score indiqué dans la case bonus, il ne prend en compte que la case Base.

**Comment by ZigmundKreud** [comment]
Le score de PC actuel correspond à la valeur courante de PC restants pour un PJ donné.
Sa valeur doit être gérée à la main et n'est donc pas calculée automatiquement (sauf à la création de la feuille de perso).
