### ISSUE TITLE
Bourse : Décalage avec les pièces

### ISSUE THREAD

**Issue by Antwan37** [ZigmundKreud/cof#22]
Mes joueurs ont eu du mal avec le système de la bourse. Les pièces et leur nombres sont décalés. Si bien que pour bcp quand ils mettent 2PA cela se transforme en fait en 2PO. Je t'envoie l'illustration sur discord

**Comment by ZigmundKreud** [comment]
OK j'ai fait en sorte que la valeur soit collée à l'icône pour plus de lisibilité.
