### ISSUE TITLE
Modif de DM au jet d'attaque

### ISSUE THREAD

**Issue by ph0k** [ZigmundKreud/cof#25]
Il est actuellement impossible de modifier les dommages lors du jet d'attaque. Est-ce qu'il serait possible de rajouter la même ligne de modification des DM sur le jet d'attaque, que lors du jet de DM ? 
Ex : Ennemi intime du rôdeur (traqueur, rang2) qui demande à changer et le jet d'attaque et le jet de DM pourrait se faire d'un coup.

**Comment by ZigmundKreud** [comment]
Fixed !
