### ISSUE TITLE
Ajout de la subcategory Potion

### ISSUE THREAD

**Issue by BlahBlah314** [ZigmundKreud/cof#26]
Il pourrait être intéressant de rajouter une subcategory potion dans les fiches d'items. En définissant la propriété de celle-ci simplement pour le moment par "soin" ou "sort", puis décrivant la formule de l'effet (au moins pour le cas "soin", la description de l'item pouvant suffire pour le moment concernant les sorts). Cela permettrait éventuellement une plus simple gestion des consommables via des macros en plus d'enrichir la création d'items.

**Comment by ZigmundKreud** [comment]
J'ai rajouté la catégorie d'items "consommable" qui est plus large que "potion".
Par contre pour la gestion des effets, c'est un peu plus compliqué, je m'en occuperai en même temps que la gestion des capacités.
En attendant je ferme ton issue.
J'ai reporté le reste de ta demande dans l'issue suivante : https://github.com/ZigmundKreud/cof/issues/28
