### ISSUE TITLE
Fiches Rencontres "Encounter"

### ISSUE THREAD

**Issue by Antwan37** [ZigmundKreud/cof#27]
Voir si possibilités : 

- Les rangs de boss n'ont pas la bonne significations : il faudrait mettre les 5 rangs de puissance (Remarquable/Supérieure/Majeure/Exceptionnelle/Légendaire) P. 217 du livre de règle.
-

**Comment by ZigmundKreud** [comment]
Les rangs étaient déjà présents, mais je les ai mis sous forme d'un menu déroulant pour plus de lisibilité.
