### ISSUE TITLE
Ajouter la possibilité de gérer des effets de soins/améliorations instantanés ou temporaires liés à des consommables.

### ISSUE THREAD

**Issue by ZigmundKreud** [ZigmundKreud/cof#28]
Ajouter la fonction "consommer" sur un item de type consommable et appliquer un effet magique de type "sort", "soin" ou "amélioration", dans la mesure du possible.

**Comment by Qaw** [comment]
Déjà en place pour les Soins.
Pour les sorts, ce sera un autre mécanisme.
Pour les améliorations, ce sera les Active Effects ou un autre mécanisme spécifique.
