### ISSUE TITLE
[enhancement] Gestion inventaire

### ISSUE THREAD

**Issue by ph0k** [ZigmundKreud/cof#29]
Proposition : afficher l'inventaire avec des sous-catégories pour améliorer sa visibilité. Bandeau repliable par catégories et nbr d'items présents sous chaque bandeau, affiché dans le bandeau.

**Comment by ph0k** [comment]
haha j'ai pas trouvé comment mettre le label gniéé

**Comment by ZigmundKreud** [comment]
Done
