### ISSUE TITLE
appliquer les dégats ou soins en un clic droit

### ISSUE THREAD

**Issue by temvaryen** [ZigmundKreud/cof#31]
A la manière de ce qui se fait pour DD5 serait il possible si on fait un clic droit sur le chat dans une fenêtre de dégâts d'obtenir ce genre d'automatisation ?
![appliquer](https://user-images.githubusercontent.com/14819124/105063577-2b125b80-5a7c-11eb-90cc-97348e4099a2.png)

**Comment by ZigmundKreud** [comment]
Done !
Ce sera ajouté dans la version 0.4
