### ISSUE TITLE
Corriger le compendium d'équipement

### ISSUE THREAD

**Issue by ZigmundKreud** [ZigmundKreud/cof#34]
Gérer les nouvelles propriétés des items dans le compendium d'équipement.

**Comment by revilofr** [comment]
Bonjour, du coup la question : existe t'il un compendium déjà fait?

**Comment by Qaw** [comment]
Oui, le module Chroniques Oubliées Fantasy - SRD est disponible directement dans Foundry

**Comment by revilofr** [comment]
Merci infiniment pour cette réponse que j'aurais du quérir bien plus tôt, ça m'aurait évité de tout rentrer moi même...
ahah

**Comment by revilofr** [comment]
Merci pour cet énorme travail, j'ai pu vérifier que ça fonctionnait bien mais je me suis rendu compte d'un problème peut être lié au compendium.
Lorsque je prends un monstre du compendium de rencontre (par exemple un Orgre) et que je clique sur sa capacité depuis l'onglet capacité de sa feuille de NPC par exemple "Imparable". Je n'en ai pas le descriptif. 

Autre question/suggestion  : Concernant les NPC sde rencontre il manque peut être une catégorie stratégie de manière à ce que le MJ sache quelle va être sa stratégie de combat (telle qu'elle est présenté dans la boite de base de Chroniques Oubliées

**Comment by revilofr** [comment]
Petit complément d'information : Si préalablement, je prends le soin d'instancier le monstre dans mon "Actor directory", alors le click sur les capacités déroule bien le descriptif de la capacité.

Il s'agit peut être plus un bug de Foundry VTT que du système..

**Comment by Qaw** [comment]
N'hésites pas à venir sur le Discord de la Fonderie pour échanger plus facilement

**Comment by revilofr** [comment]
ok j'arrive :)

**Comment by Qaw** [comment]
Le compendium est géré sur un autre repository
