### ISSUE TITLE
Interdire/limiter l'utilisation des boutons dans les box de dialogue

### ISSUE THREAD

**Issue by Dolgren** [ZigmundKreud/cof#36]
Interdire (ou limiter au personnage concerné) l'utilisation des boutons de déduction ou d'incrémentation des points de vie pour les joueurs dans les box de discussion.

**Comment by Qaw** [comment]
Une option va être ajoutée qui permet de choisir si l'affichage est pour tout le monde. Sinon les boutons ne seront affichés qu'au MJ.

**Comment by Qaw** [comment]
Corrigé en 0.5.0
