### ISSUE TITLE
Colorisation des résultats critiques dans la box des jets

### ISSUE THREAD

**Issue by Dolgren** [ZigmundKreud/cof#37]
Coloriser en vert les jets avec 20 naturel et en rouge les jets avec 1 naturel (la colorisation se fait sur le résultat final jet + éventuel bonus).

**Comment by MadHatt3rs** [comment]
En attente d'implémentation voir [https://github.com/ZigmundKreud/cof/pull/45](url)

**Comment by Qaw** [comment]
C'était déjà le cas. Il y avait un bug où le fumble n'était pas affiché si la difficulté ne l'était pas. Ca sera corrigé dans la prochaine version.

**Comment by Qaw** [comment]
Corrigé en 0.5.0
