### ISSUE TITLE
Prendre en compte les malus d'armure/bouclier sur les jets de DEX

### ISSUE THREAD

**Issue by skitoo** [ZigmundKreud/cof#38]
Lorsque l'on porte une armure ou un bouclier, un malus doit être appliqué sur les jet de DEX. Il serait bien que le système le prenne en charge automatiquement.

Merci encore pour le taf accompli :)

**Comment by Italemyae** [comment]
Bonjour, 

Attention à rendre cette valeur de malus d'armure accessible par effet pour pouvoir la limiter (chevalier/voie de la guerre rang 1 : armure sur mesure - seule la moitié de la valeur de DEF est appliquée comme malus)

**Comment by Qaw** [comment]
Prévu dans la prochaine version pour le calcul automatique.
Pour l'affichage accessible, il faut encore qu'on y réfléchisse.

**Comment by Qaw** [comment]
Corrigé en 0.5.0
