### ISSUE TITLE
Commandes tchat ne fonctionnent plus

### ISSUE THREAD

**Issue by Rehvaro** [ZigmundKreud/cof#4]
Bonjour,

Je voudrais signaler un soucis.

J'utilise la dernière version stable de Foundry : 0.6.6

Si je créait un nouveau monde en utilisant le GameSystem COF, alors les commandes tchat ne fonctionnent plus. Rien ne s'affiche dans le tchat. Plus de /roll, ou même de simple messages. 
Les jets se font par contre depuis les boutons (Par exemple Force, ou Contact) des fiches de personnage.
Je n'ai activé aucun module.
Cela fonctionne si je créais un monde avec un autre GameSystem.

Cordialement,
Rehvaro

**Comment by ZigmundKreud** [comment]
OK j'ai vu le pb et c'est corrigé dans la version 0.1.2-beta.
