### ISSUE TITLE
PV max = PV Base

### ISSUE THREAD

**Issue by Italemyae** [ZigmundKreud/cof#42]
Bonjour, 

J'ai un magelame qui a monté sa voie de la robustesse. Pour symboliser le truc, il a ses PV de base, un bonus ce qui lui donne un confortable total de PV max. 

Mais hier, en partie, impossible de le soigner complètement. En tentant de mettre la valeur Y (PV Max) dans Actuels, la valeur de retrouve limité a X (PV Base) lors de la validation. 

A noter qu'en répétant plusieurs fois l'opération j'arrive à afficher la valeur Y dans Actuels mais ça ne semble pas validé (et mon joueur ne voit que la valeur limité X de son côté). 

Merci encore pour le système, tout le reste fonctionne bien ! 

Italemyae / Calandil

**Comment by MadHatt3rs** [comment]
Tu est sur qu'elle version ? Foundry et COF
Tu a tester en désactivant t'ai modules ?
J'ai tester chez moi sur deux serveur différent ça fonctionne très bien.
![issue 42](https://user-images.githubusercontent.com/14993519/110606015-0ab47280-818a-11eb-9902-766cf5c325e0.PNG)

**Comment by MadHatt3rs** [comment]
Merci j'ai mieux compris t'on problème ;)
Effectivement ça ne fonctionne pas avec les effets il me semble avoir trouver la cause.
Je lance des test de mon coté avec mes joueur et je proposerais une PR.
P.S : idem pour les test d'attaques

**Comment by MadHatt3rs** [comment]
En attente d'implémentation voir [https://github.com/ZigmundKreud/cof/pull/44](url)

**Comment by Qaw** [comment]
Juste une remarque, pourquoi ne pas ajouter le bonus via l'effet uniquement au bonus ?
Le max sera alors mis à jour automatiquement non ?

**Comment by ZigmundKreud** [comment]
Ce qu'il faut comprendre c'est que les valeurs de base et les valeurs max sont calculées automatiquement par le système.
Du coup, il suffit d'utiliser le champ "bonus" et ça va augmenter mécaniquement la valeur "max".
Ca se passe dans le fichier suivant. à la ligne 220 : https://github.com/ZigmundKreud/cof/blob/master/module/actors/actor.js#L220

**Comment by MadHatt3rs** [comment]
@ZigmundKreud @Qaw  Avez-vous testé de modifier la valeur bonus de vie avec un **active effect** ?
Ou encore les valeurs d'attributs ? Ou les valeurs d'attaques ? Sur la branche actuelle cela ne fonctionne pas.
J'ai corrigé ce petit défaut dans la PR #44.

**_Branch master :_** 
![image](https://user-images.githubusercontent.com/14993519/111539044-bbfc6f00-876d-11eb-9e2c-c709bb5a7f4a.png)

**_PR #44 :_** 
![image](https://user-images.githubusercontent.com/14993519/111539224-e817f000-876d-11eb-8cc3-cf1956be55d5.png)

**Comment by Qaw** [comment]
Comment obtiens-tu la fenêtre Configure Active Effect ?

**Comment by MadHatt3rs** [comment]
@Qaw 
![image](https://user-images.githubusercontent.com/14993519/111544954-92dfdc80-8775-11eb-8e4a-a13b5b03fec7.png)

**Comment by Qaw** [comment]
Ha oui je cherchais via les objets. Tu as essayé en ajoutant une durée ? C'est obligatoire pour que ce soit pris en compte.

**Comment by MadHatt3rs** [comment]
Regarde la PR que j'ai liée à mes messages le problème y est résolue...

**Comment by Qaw** [comment]
Je clos ce ticket car le problème initial n'en est pas un.
Pour les effets, il y a déjà une PR en cours.
