### ISSUE TITLE
Proposition : Ajouter une colonne "Bonus Mod" dans la feuille de perso.

### ISSUE THREAD

**Issue by MadHatt3rs** [ZigmundKreud/cof#47]
Dans la version actuelle la colonne "Bonus" des caractéristiques modifie la valeur de base de la caractéristique, et le bonus du modificateur de caractéristique ne peut s'appliquer que dans la dialog.

Seulement il n'est pas possible d'appliquer un Active effect dans la dialog directement et, certaines compétences demandent d'appliquer un bonus au modificateur directement. (Voir [Bénédiction](http://co-drs.org/capacites/benediction/) ou encore [Dur à cuire](http://co-drs.org/capacites/dur-a-cuire/)) Et d'autre à la valeur de caractéristique de base (Voir [Constitution héroïque](http://co-drs.org/capacites/constitution-heroique/))

Maquette pour l'exemple : 
![image](https://user-images.githubusercontent.com/14993519/111313971-42775a80-8661-11eb-9567-cd06610d33df.png)

Qu'en pensez-vous ?

**Comment by Qaw** [comment]
Alors les bonus aux tests de caractéristiques sont différents des bonus au Mod.
Bon pour Bénédiction, ça pourrait effectivement revenir au même.
Par contre pour Dur à cuir, c'est uniquement sur le jet.
On a ajouté les malus au jet de FOR et DEX sur la version en cours. Je prévois d'ajouter les bonus/malus au jet pour la suite.
