### ISSUE TITLE
Suppression de la Race ou du Profil sans avoir coché de voies

### ISSUE THREAD

**Issue by Qaw** [ZigmundKreud/cof#48]
C'est le même comportement pour la race ou le profil : je vais donc parler uniquement de race.
Si après avoir ajouté une race, je sélectionne des voies et qu'ensuite je supprime la race : tout se passe bien, la race est supprimée ainsi que les voies.
Par contre, si j'ajoute la race, et que je la supprime toute de suite. La race est bien supprimée mais les voies restent.

**Comment by HenriotJerome** [comment]
Corrigé sur COF pour la suppression de la race/peuple et du profil.
