### ISSUE TITLE
Header fenetre Journal Image - Mauvaise couleur de texte

### ISSUE THREAD

**Issue by Rehvaro** [ZigmundKreud/cof#5]
Bonjour,

Je voudrais signaler un soucis que j'ai constaté:

Il semblerait que quand on utilise le système de jeu COF, le texte dans le header des fenêtres de journal en mode image est alors écrit en sombre sur sombre, au lieu de blanc sur sombre, ce qui gène la lecture.

COF : 
![exemple](https://user-images.githubusercontent.com/1692086/95261578-ec3cfa80-082a-11eb-9f68-ad83b2ac371e.png)
Sandbox: 
![exemple2](https://user-images.githubusercontent.com/1692086/95261677-1c849900-082b-11eb-8b1c-96aa2653a298.png)

Cordialement,
Rehvaro

**Comment by Antwan37** [comment]
Effectivement j'ai le même affichage

**Comment by ZigmundKreud** [comment]
C'est corrigé.
