### ISSUE TITLE
affectation du modérateur d'attaque

### ISSUE THREAD

**Issue by kroglethane** [ZigmundKreud/cof#6]
Bonjour ZikmundKreug,

tout d'abord merci pour le boulot. La fiche est top.

Ma remarque porte sur l'affectation du modérateur d'attaque au niveau des armes.
Il reste à 1, le MOD du type d'attaque n'est pas pris en compte. 
Pour parer  à cela j'ajoute un bonus dans la case compétence.

Comme le MOD. de caractéristique est pris en compte pour les dégâts, je suppose que cela devrait-être identique pour l'attaque.

Kroglethane

**Comment by ZigmundKreud** [comment]
Oui c'est un bug qui est lié à la nouvelle version 0.7.*
Je suis en train d'essayer de trouver pourquoi les valeurs de mes attributs ne sont pas pris en compte...
J'ai posé la question sur le discord officiel, j'ai pas eu de réponse.

**Comment by ZigmundKreud** [comment]
Je l'ai fermée un peu vite :)

**Comment by ZigmundKreud** [comment]
C'est corrigé dans la nouvelle release
