### ISSUE TITLE
Problème attaque Combat corps à corps

### ISSUE THREAD

**Issue by Antwan37** [ZigmundKreud/cof#7]
[https://media.discordapp.net/attachments/724327168573964294/766202095824142336/IMG_20201015_093212.jpg?width=434&height=579](url)

Salut Zigmund,
Il y a un soucis quand le mod d'attaque est à 0. C'est le cas sur mon elfe Maëla des pré-tirés.
Sa valeur de Combat physique est à 0.
Le lanceur de dé via le bâton refuse de se lancer avec un message d'erreur.
Si je passe le mod à -1 par exemple cela fonctionne

**Comment by ZigmundKreud** [comment]
OK j'ai trouvé. Ce sera corrigé dans le prochain patch.
