### ISSUE TITLE
Compatibilité Foundry 0.8.6

### ISSUE THREAD

**Issue by cbricojdr** [ZigmundKreud/cof#76]
Bonjour,

Le portage de COF sur Foundry est limité à la version 0.7.10
Hors de nombreux modules ont été mis à jour sur la dernière version et ne sont plus disponibles pour COF
Est-il prévu une mise à jour du module COF pour être compatible avec la dernière version ?

En vous remerciant par avance

**Comment by HenriotJerome** [comment]
Le développement pour la portabilité en 0.8.7 est en cours, patiente.

**Comment by cbricojdr** [comment]
Merci de la réponse

Bonne journée

**Comment by HenriotJerome** [comment]
C'est disponible, bon test et jeu
