### ISSUE TITLE
0.8.7.1 - Erreur JS Drag&Drop Combat Rencontre

### ISSUE THREAD

**Issue by CrapalZ** [ZigmundKreud/cof#77]
Lors d'un test de drag & drop d'une attaque d'un PNJ vers la macrobar, la console renvoie
```
Uncaught TypeError: Cannot read property 'data' of undefined
    at CofActorSheet._onDragStart (foundry.js:24294)
    at DragDrop.callback (foundry.js:20789)
    at DragDrop._handleDragStart (foundry.js:20814)
```
Il me semble qu'il n'est toujours pas possible de drag&drop une attaque de pnj vers la macrobar, reste le fait qu'une erreur apparaît

**Comment by HenriotJerome** [comment]
Demande de précision : 
Tu es sur système COF et module COF-SRD ou système COF et module COTA ?  
Je viens d'essayer sur les deux et je n'ai pas eut de message d'erreur.
Envoi un impression écran que l'on essaye de reproduire en visible la race et le profil et l'arme utilisée

RAPPEL : IL NE FAUT PAS AVOIR LES DEUX MODULES DE SELECTIONEE, C'EST SOIT L'UN SOIT L'AUTRE

**Comment by CrapalZ** [comment]
Correction, c'est sur un acteur de type Rencontre.
Les attaques des acteurs de type Rencontre ne peuvent pas être placées dans la macrobar, toutefois, ce bug apparaît dès lors qu'on drag une attaque, et non au moment du drop.

**Comment by CrapalZ** [comment]
Ça fait surement écho au #65. Si vous le considérez comme un doublon vous pouvez le fermer

**Comment by HenriotJerome** [comment]
Oui c'est normal, une attaque de rencontre n'est pas un item, donc ne peux pas être drag&drop.
C'est l'objet d'une évolution prochaine de mettre les attaques de rencontre en Item. Patiente.

**Comment by Qaw** [comment]
Doublon de #65 effectivement. Je le clos
