### ISSUE TITLE
Partie basse des acteurs tronquée

### ISSUE THREAD

**Issue by CrapalZ** [ZigmundKreud/cof#79]
Les onglets Inventaire et Voies & Capacités affichant des listes plus longues que la hauteur de la fiche sont tronquées en bas de page malgré l’ascenseur
[Exemple](https://i.imgur.com/X1mgWNP.png)

Le dernier item apparaît systématiquement tronqué.

**Comment by HenriotJerome** [comment]
Non reproduis sur les navigateur Edge et Chrome
Quel navigateur utilises-tu ?

**Comment by CrapalZ** [comment]
Je le reproduis sur edge et l'appli foundryvtt

**Comment by Qaw** [comment]
Ca vient du module Compendium Folders, qui utilise lui aussi la classe CSS .compendium-pack
Le nom sera renommé .cof-compendium-pack
