### ISSUE TITLE
Encounters : Test de Carac impossible

### ISSUE THREAD

**Issue by Antwan37** [ZigmundKreud/cof#8]
Lors de l'utilisation des encounters, ceux-ci ne peuvent pas lancer de test de caractéristique.
On ne peux pas faire un test de force opposé directement via la fiche par exemple.

La fonction marche sur les PNJ mais pas pour la fiche encounters

**Comment by ZigmundKreud** [comment]
C'est corrigé !

**Comment by ZigmundKreud** [comment]
Je précise que le correctif n'est pas encore déployé. Il faudra attendre la prochaine release.

**Comment by Antwan37** [comment]
Toujours top
