### ISSUE TITLE
0.8.7.1 - Agrandir une catégorie agrandit toutes les catégories

### ISSUE THREAD

**Issue by CrapalZ** [ZigmundKreud/cof#80]
Lorsqu'on réduit plusieurs catégories (inventaire ou voies & capacités) puis qu'on en agrandit une seule, elles sont toutes agrandit, tous onglets confondus.

**Comment by HenriotJerome** [comment]
Désolé, je ne comprend pas  !!!!

**Comment by CrapalZ** [comment]
Dans la vidéo ci-dessous, je reproduis le problème... ainsi que le problème de l'issue #79 
https://youtu.be/hfTsdnXLvEo

**Comment by Qaw** [comment]
Merci pour la vidéo. Super idée.
