### ISSUE TITLE
0.8.7.1 - Possible de dépasser les PV max d'une rencontre mais pas d'un PJ

### ISSUE THREAD

**Issue by CrapalZ** [ZigmundKreud/cof#81]
L'impossibilité de dépasser le nombre de PV max est présente sur les fiches des PJ, mais ne l'est pas sur les rencontres.
Il faudrait peut être appliquer ce cap à tous les types d'acteur

**Comment by HenriotJerome** [comment]
Il me semble que les créatures ne sont pas soumis à cette règle, les point de vie ne sont pas issue de calcul mais libre.

**Comment by HenriotJerome** [comment]
Oui effectivement ce serait mieux :).
