### ISSUE TITLE
Ajouter la notion d'affaiblissement (remplacer le D20 par un D12)

### ISSUE THREAD

**Issue by Eryan9** [ZigmundKreud/cof#99]

**Comment by Qaw** [comment]
L'idée serait que le d12 soit automatiquement sélectionné comme type de dé si un statut Affaibli est activé ?

**Comment by Eryan9** [comment]
Les états : 
**Affaibli** : utiliser un d12 pour tous les tests au lieu du d20.
**Immobilisé** : pas de déplacement et utiliser un d12 pour tous les tests au lieu du d20.

Demandent de remplacer le D20 par D12 pour tous les jets
Il faudrait donc dans les différentes fonction de roll pouvoir remplacer le D20 de base par un D12
En gros je pense un simple paramètre en plus dans les fonction pour faire la bascule et pouvoir ignorer le malus à la demande 
Ainsi qu'un endroit dans la fiche de perso pour activer/désactiver l'état affaibli (a moins que l'on se serve des icones de statut sur le token)
